### ISSUE TITLE
Css doesn't connect up.

### ISSUE THREAD

**Issue by mrmurphy** [prose/starter#1]
Hey there! I've forked the repository, and changed the _config, just as directed. But my css doesn't seem to connect up. This is wat I get:  

http://murphyrandle.com/bootstrap/

Thanks!

---

**Comment by mrmurphy** [comment]
I realized that I needed to enter the full address to my github repo site in the _yaml file for the root attribute. This allowed all links to work correctly.

**Comment by dittaeva** [comment]
Please reopen this. Either the guide needs fixing or the setup isn't working as it should. I had the same problem.
