### ISSUE TITLE
`/starter' not found.

### ISSUE THREAD

**Issue by stepankuzmin** [prose/starter#21]
I've cloned repo, started `jekyll serve --watch`, went to `http://localhost:4000/starter` and get 404 error page ``/starter' not found.`

**Comment by tristen** [comment]
The server instance that starts requires a forward slash. Can you try: `http://localhost:4000/starter/` ?

**Comment by stepankuzmin** [comment]
Same error on `http://localhost:4000/starter/`
But it works if I start jekyll with empty base url: `jekyll serve --baseurl ''`

**Comment by cew821** [comment]
I just submitted a pull request for the same issue #22 ; but for me visiting `http://localhost:4000/starter/` worked.

**Comment by fenix011** [comment]
Same happened here... The suggested trick worked for me also. Thanks!
