### ISSUE TITLE
Image upload in metadata config panel

### ISSUE THREAD

**Issue by hanserino** [prose/starter#38]
Would it be possible to include an image upload button to the metadata panel? As I understand it, the only way to dedicate a specific image as a metadata item is to paste the url of the image to a text input. But non-developers will probably find this a bit confusing. I see in your example project that you have a text input for your splash image.

**Comment by dereklieu** [comment]
This feature request belongs in the [prose issue queue](https://github.com/prose/prose/issues). Personally, while I'm not against the idea of an image upload metadata element, it's not on my list of priorities. Feel free to open a ticket there though.
