### ISSUE TITLE
Adding TITLE attribute when inserting external link breaks the link

### ISSUE THREAD

**Issue by ctxlken** [prose/starter#39]
When inserting an external link, if the URL and link text fields are supplied, that is fine, but if the title field is also supplied, the output for the link is incorrect, resulting in double-quotes in the wrong place and resulting in no 'title' attribute as would be expected.

**Comment by dereklieu** [comment]
I think this issue belongs in [prose/prose](https://github.com/prose/prose). 

@ctxlken can you please open the issue there and be very specific about 1. what text input you're using, 2. what you expected it to produce, and 3. what actually came out.
