### ISSUE TITLE
Could not find gem github-pages

### ISSUE THREAD

**Issue by tonyatoms** [prose/starter#44]
Installing the starter project per the instructions in the README and trying to run it  via
 `bundle exec Jekyll serve` results in this failure:
`Could not find gem 'github-pages' in any of the gem sources listed in your Gemfile.`

This is of particular interest to me as I do not intend to use Prose for a GitHub-pages hosted site, at least not initially.
EDIT: env details
`ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]`

**Comment by tonyatoms** [comment]
I was able to resolve this (and a subsequent issue) by adding a Gemfile with these contents:
```
source 'https://rubygems.org'
gem 'github-pages'
gem 'rdiscount'
```
and then running `bundle install`

**Comment by dereklieu** [comment]
@tonyatoms hey, thanks for raising this. It looks like we should actually just retire the use of `rdiscount` and allow jekyll to use it's default markdown engine, `kramdown`.

https://blog.github.com/2016-02-01-github-pages-now-faster-and-simpler-with-jekyll-3-0/

This should also make the build simpler.

**Comment by brando90** [comment]
I get a different issue:

```
$ bundle update github-pages
Could not find gem 'github-pages'.
```

any idea how to solve it?

**Comment by dereklieu** [comment]
Do you have the github-pages gem installed? I'm not sure but I'd bet you would need to have it installed before it could be updated.

**Comment by ghost** [comment]
this worked for me 
**specify the version for gem "github-pages" in GEMFILE**:
`gem "github-pages", "~> 203", group: :jekyll_plugins`
replace the version ( **203** ) above to the one from [https://pages.github.com/versions/](https://pages.github.com/versions/)
**then run:** 
`bundle update jekyll`
**followed by :** 
`bundle install`
**test site by launching it locally :** 
`bundle exec jekyll serve`

**Comment by Rubix982** [comment]
Worked perfectly. Thank you, @the-po .

**Comment by yuqli** [comment]
Thanks @six-ten for solving my problems!

**Comment by AveryQi115** [comment]
if you have installed jekyll 4.1.1 before create your github pages project
and therefore there might be some conflicts between existing gems and gems needed for github pages.

@six-ten 's answer works fine but needs to change the command:
`bundle update jekyll`
to:
`bundle update`
so it will build your snapshot from scratch.

**Comment by vaibhavsabnis** [comment]
there are some version conflicts when installing ruby and bundler (which in turn installs jekyll 4.2.0 - as of Dec 30 2020). This version conflicts with what github needs - so @six-ten comments may not work out of the box. 
Below is what i did to resolve: 
1. updated the version of github-pages so that the gem is correctly updated (209 as of this writing)
2. Ran following cmd from the local repo root 
--> bundle update github-pages 
--> bundle install
--> bundle update

**Comment by silndoj** [comment]
echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc

(if you have an .zsh be sure to replace .bashrc with .zshrc)
